name: TheWalls
main: com.github.JHXSMatthew.Main
depend: []
version: 0.0.1-SNAPSHOT
commands:
  walls:
    description: Main command!
    aliases: [wall]
  likai:
    description: Main command!
    aliases: [likai]